export const COMMON_LABELS = {
  action: {
    save: 'Lưu',
    cancel: 'Hủy',
    create: 'Tạo mới',
    update: 'Cập nhật',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    view: 'Xem',
    close: 'Đóng',
    confirm: 'Xác nhận',
    search: 'Tìm kiếm',
    filter: 'Lọc',
    reset: 'Đặt lại',
    saving: 'Đang lưu...',
    deleting: 'Đang xóa...',
  },
  status: {
    label: 'Trạng thái',
    active: 'Hoạt động',
    inactive: 'Ngừng hoạt động',
  },
  validation: {
    required: (field: string) => `${field} là bắt buộc`,
    invalidEmail: 'Email không hợp lệ',
    maxLength: (field: string, max: number) => `${field} không được quá ${max} ký tự`,
  },
  field: {
    name: 'Họ và tên',
    email: 'Email',
    phone: 'Số điện thoại',
    position: 'Chức vụ',
    description: 'Mô tả',
    status: 'Trạng thái',
  },
  table: {
    noData: 'Không có dữ liệu',
    loading: 'Đang tải...',
    columns: 'Cột',
    showColumns: 'Hiển thị cột',
    clearFilter: 'Xóa bộ lọc',
  },
  confirm: {
    deleteTitle: 'Xác nhận xóa',
    cannotUndo: 'Hành động này không thể hoàn tác.',
    discardTitle: 'Dữ liệu không được lưu',
    discardDescription: 'Bạn có thay đổi chưa được lưu. Bạn có chắc muốn đóng và bỏ các thay đổi này không?',
    discardConfirm: 'Không lưu',
  },
} as const;
