export const ENGAGEMENT_LABELS = {
  engagement: {
    title: 'Cuộc kiểm toán',
    titlePlural: 'Danh sách cuộc kiểm toán',
    createTitle: 'Tạo cuộc kiểm toán mới',
    editTitle: 'Chỉnh sửa cuộc kiểm toán',
    deleteTitle: 'Xóa cuộc kiểm toán',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa cuộc kiểm toán "${name}"? Tất cả dữ liệu liên quan sẽ bị xóa.`,
    noData: 'Chưa có cuộc kiểm toán nào.',
    search: 'Tìm kiếm cuộc kiểm toán...',
    field: {
      title: 'Tiêu đề',
      entity: 'Đối tượng kiểm toán',
      objective: 'Mục tiêu',
      scope: 'Phạm vi',
      startDate: 'Ngày bắt đầu',
      endDate: 'Ngày kết thúc',
      schedule: 'Lịch trình',
      status: 'Trạng thái',
      priority: 'Ưu tiên',
      estimatedDays: 'Số ngày dự kiến',
      notes: 'Ghi chú',
      linkedPlan: 'Kế hoạch liên kết',
      createdAt: 'Ngày tạo',
      updatedAt: 'Cập nhật',
    },
    status: {
      planning: 'Lập kế hoạch',
      fieldwork: 'Thực hiện',
      review: 'Soát xét',
      reporting: 'Báo cáo',
      closed: 'Đã đóng',
    } as Record<string, string>,
    priority: {
      high: 'Cao',
      medium: 'Trung bình',
      low: 'Thấp',
    } as Record<string, string>,
    tab: {
      planning: 'Kế hoạch',
      execution: 'Thực hiện',
      findings: 'Phát hiện',
      reporting: 'Báo cáo',
    },
  },
  section: {
    title: 'Phần hành',
    createTitle: 'Phần hành',
    editTitle: 'Chỉnh sửa phần hành',
    deleteTitle: 'Xóa phần hành',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa phần "${name}"? Tất cả mục tiêu và thủ tục bên trong cũng sẽ bị xóa.`,
    field: {
      title: 'Tên phần hành',
      description: 'Mô tả',
      status: 'Trạng thái',
    },
  },
  objective: {
    title: 'Mục tiêu',
    createTitle: 'Mục tiêu',
    editTitle: 'Chỉnh sửa mục tiêu',
    deleteTitle: 'Xóa mục tiêu',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa mục tiêu "${name}"? Tất cả thủ tục bên trong cũng sẽ bị xóa.`,
    field: {
      title: 'Tên mục tiêu',
      description: 'Mô tả',
      status: 'Trạng thái',
    },
  },
  procedure: {
    title: 'Thủ tục kiểm toán',
    createTitle: 'Thủ tục',
    editTitle: 'Chỉnh sửa thủ tục',
    deleteTitle: 'Xóa thủ tục',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa thủ tục "${name}"?`,
    field: {
      title: 'Tên thủ tục',
      description: 'Mô tả chi tiết',
      procedures: 'Thủ tục thực hiện',
      procedureType: 'Loại thủ tục',
      status: 'Trạng thái',
      observations: 'Quan sát / Kết quả',
      conclusion: 'Kết luận',
      effectiveness: 'Kết quả đánh giá',
      evidences: 'Bằng chứng',
      workpaper: 'Work Papers',
      sampleSize: 'Cỡ mẫu',
      exceptions: 'Số ngoại lệ',
      priority: 'Ưu tiên',
      reviewNotes: 'Ghi chú soát xét',
      performedBy: 'Người thực hiện',
      reviewedBy: 'Người soát xét',
      performedAt: 'Ngày thực hiện',
      reviewedAt: 'Ngày soát xét',
    },
    procedureType: {
      inquiry: 'Phỏng vấn',
      observation: 'Quan sát',
      inspection: 'Kiểm tra tài liệu',
      re_performance: 'Thực hiện lại',
      analytical: 'Phân tích',
      walkthrough: 'Kiểm tra xuyên suốt',
      other: 'Khác',
    } as Record<string, string>,
    procedureCategory: {
      toc: 'Kiểm tra kiểm soát (TOC)',
      substantive: 'Kiểm tra cơ bản',
    } as Record<string, string>,
    status: {
      not_started: 'Chưa bắt đầu',
      in_progress: 'Đang thực hiện',
      waiting_review: 'Chờ soát xét',
      needs_modification: 'Cần chỉnh sửa',
      approved: 'Đã phê duyệt',
      reviewed: 'Đã soát xét',
    } as Record<string, string>,
  },
  planning: {
    scopeBasics: 'Phạm vi kiểm toán',
    understanding: 'Tìm hiểu đối tượng',
    understandingEdit: 'Chỉnh sửa nội dung tìm hiểu',
    riskControl: 'Rủi ro & Kiểm soát (RACM)',
    procedures: 'Chương trình kiểm toán',
    areas: 'Lĩnh vực',
    noAreas: 'Chưa có lĩnh vực.',
    syncObjectives: 'Đồng bộ mục tiêu',
    noObjectives: 'Chưa có mục tiêu kiểm toán.',
    noUnderstanding: 'Chưa có nội dung tìm hiểu.',
  },
  auditObjective: {
    title: 'Mục tiêu kiểm toán',
    createTitle: 'Thêm mục tiêu kiểm toán',
    editTitle: 'Chỉnh sửa mục tiêu kiểm toán',
    deleteTitle: 'Xóa mục tiêu kiểm toán',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa mục tiêu kiểm toán "${name}"?`,
    noData: 'Chưa có mục tiêu kiểm toán nào.',
    field: {
      title: 'Tên mục tiêu',
      description: 'Mô tả',
    },
  },
  risk: {
    title: 'Rủi ro',
    createTitle: 'Thêm rủi ro',
    editTitle: 'Chỉnh sửa rủi ro',
    deleteTitle: 'Xóa rủi ro',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa rủi ro "${name}"?`,
    noData: 'Chưa có rủi ro nào.',
    field: {
      riskDescription: 'Mô tả rủi ro',
      riskRating: 'Đánh giá rủi ro',
      riskCategory: 'Phân loại rủi ro',
      likelihood: 'Khả năng xảy ra',
      impact: 'Mức độ tác động',
      controlDescription: 'Mô tả kiểm soát',
      controlEffectiveness: 'Hiệu quả kiểm soát',
      controlType: 'Loại kiểm soát',
      controlNature: 'Tính chất',
      controlFrequency: 'Tần suất',
      auditObjective: 'Mục tiêu kiểm toán',
      linkedControls: 'Kiểm soát liên quan',
      linkedRisks: 'Rủi ro liên quan',
    },
    controlEffectiveness: {
      strong: 'Mạnh',
      adequate: 'Đầy đủ',
      weak: 'Yếu',
      none: 'Không có',
    } as Record<string, string>,
    riskRating: {
      low: 'Thấp',
      medium: 'Trung bình',
      high: 'Cao',
      critical: 'Rất cao',
    } as Record<string, string>,
    riskCategory: {
      operational: 'Vận hành',
      financial: 'Tài chính',
      compliance: 'Tuân thủ',
      strategic: 'Chiến lược',
      it: 'CNTT',
    } as Record<string, string>,
    likelihood: {
      rare: 'Hiếm khi',
      unlikely: 'Ít có khả năng',
      possible: 'Có thể',
      likely: 'Có khả năng',
      almost_certain: 'Gần như chắc chắn',
    } as Record<string, string>,
    impact: {
      insignificant: 'Không đáng kể',
      minor: 'Nhỏ',
      moderate: 'Trung bình',
      major: 'Lớn',
      catastrophic: 'Thảm khốc',
    } as Record<string, string>,
    controlType: {
      preventive: 'Phòng ngừa',
      detective: 'Phát hiện',
      corrective: 'Khắc phục',
    } as Record<string, string>,
    controlNature: {
      manual: 'Thủ công',
      automated: 'Tự động',
      it_dependent: 'Phụ thuộc CNTT',
    } as Record<string, string>,
    controlFrequency: {
      continuous: 'Liên tục',
      daily: 'Hàng ngày',
      weekly: 'Hàng tuần',
      monthly: 'Hàng tháng',
      quarterly: 'Hàng quý',
      annually: 'Hàng năm',
      event_driven: 'Theo sự kiện',
    } as Record<string, string>,
  },
  control: {
    title: 'Kiểm soát',
    createTitle: 'Thêm kiểm soát',
    editTitle: 'Chỉnh sửa kiểm soát',
    deleteTitle: 'Xóa kiểm soát',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa kiểm soát "${name}"?`,
    noData: 'Chưa có kiểm soát nào.',
    unlinkTitle: 'Hủy liên kết kiểm soát',
    unlinkDescription: (name: string) =>
      `Hủy liên kết kiểm soát "${name}" khỏi rủi ro này? Kiểm soát sẽ không bị xóa.`,
    addExisting: 'Chọn kiểm soát có sẵn',
    addNew: 'Tạo kiểm soát mới',
  },
  finding: {
    title: 'Phát hiện',
    createTitle: 'Thêm phát hiện',
    editTitle: 'Chỉnh sửa phát hiện',
    deleteTitle: 'Xóa phát hiện',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa phát hiện "${name}"?`,
    noData: 'Chưa có phát hiện nào.',
    field: {
      title: 'Tiêu đề',
      description: 'Mô tả',
      riskRating: 'Mức rủi ro',
      status: 'Trạng thái',
      recommendation: 'Kiến nghị',
      managementResponse: 'Phản hồi của ban quản lý',
      rootCause: 'Nguyên nhân gốc',
      linkedProcedures: 'Thủ tục liên quan',
    },
    status: {
      draft: 'Bản nháp',
      to_review: 'Chờ soát xét',
      reviewed: 'Đã soát xét',
      accepted: 'Đã chấp nhận',
      rejected: 'Đã từ chối',
    } as Record<string, string>,
    riskRating: {
      low: 'Thấp',
      medium: 'Trung bình',
      high: 'Cao',
      critical: 'Rất cao',
    } as Record<string, string>,
  },
  versioning: {
    publish: 'Xuất bản',
    publishTitle: 'Xuất bản phiên bản',
    publishDescription: 'Tạo một phiên bản mới từ nội dung hiện tại.',
    publishComment: 'Ghi chú phiên bản',
    publishCommentPlaceholder: 'Mô tả ngắn về thay đổi...',
    publishSuccess: 'Đã xuất bản thành công',
    versionHistory: 'Lịch sử phiên bản',
    version: 'Phiên bản',
    noVersions: 'Chưa có phiên bản nào.',
    viewVersion: 'Xem phiên bản',
    restoreVersion: 'Khôi phục phiên bản',
    restoreTitle: 'Khôi phục phiên bản',
    restoreDescription: (v: number) =>
      `Bạn có chắc chắn muốn khôi phục phiên bản ${v}? Nội dung hiện tại sẽ bị ghi đè.`,
    restoreSuccess: 'Đã khôi phục thành công',
    publishedBy: 'Xuất bản bởi',
    publishedAt: 'Ngày xuất bản',
  },
  approval: {
    approvalStatus: 'Trạng thái phê duyệt',
    status: {
      draft: 'Bản nháp',
      waiting_review: 'Chờ soát xét',
      needs_modification: 'Cần chỉnh sửa',
      reviewed: 'Đã soát xét',
      waiting_approval: 'Đợi phê duyệt',
      approved: 'Đã phê duyệt',
    } as Record<string, string>,
    transitionSuccess: 'Đã chuyển trạng thái thành công',
    approvedBy: 'Phê duyệt bởi',
    approvedAt: 'Ngày phê duyệt',
    approvedVersion: 'Phiên bản phê duyệt',
    noTransitions: 'Không có hành động khả dụng',
  },
} as const;
