export const PLAN_LABELS = {
  plan: {
    title: 'Kế hoạch kiểm toán',
    titlePlural: 'Danh sách kế hoạch',
    createTitle: 'Tạo kế hoạch mới',
    editTitle: 'Chỉnh sửa kế hoạch',
    deleteTitle: 'Xóa kế hoạch',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa kế hoạch "${name}"? Tất cả kế hoạch cuộc kiểm toán bên trong cũng sẽ bị xóa.`,
    noData: 'Chưa có kế hoạch kiểm toán nào.',
    search: 'Tìm kiếm kế hoạch...',
    field: {
      title: 'Tên kế hoạch',
      description: 'Mô tả',
      periodType: 'Loại kỳ',
      periodStart: 'Bắt đầu',
      periodEnd: 'Kết thúc',
      period: 'Kỳ kế hoạch',
      status: 'Trạng thái',
      auditCount: 'Số kế hoạch cuộc kiểm toán',
      progress: 'Tiến độ',
      createdAt: 'Ngày tạo',
      updatedAt: 'Cập nhật',
    },
    periodType: {
      annual: 'Năm',
      quarterly: 'Quý',
      monthly: 'Tháng',
      custom: 'Tùy chỉnh',
    } as Record<string, string>,
    status: {
      draft: 'Bản nháp',
      approved: 'Đã duyệt',
      in_progress: 'Đang thực hiện',
      closed: 'Đã đóng',
    } as Record<string, string>,
  },
  audit: {
    title: 'Kế hoạch cuộc kiểm toán',
    createTitle: 'Thêm kế hoạch cuộc kiểm toán',
    editTitle: 'Chỉnh sửa kế hoạch cuộc kiểm toán',
    deleteTitle: 'Xóa kế hoạch cuộc kiểm toán',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa kế hoạch cuộc kiểm toán "${name}" khỏi kế hoạch?`,
    noData: 'Chưa có kế hoạch cuộc kiểm toán nào.',
    createEngagement: 'Tạo cuộc kiểm toán',
    field: {
      entity: 'Đối tượng kiểm toán',
      title: 'Tiêu đề',
      objective: 'Mục tiêu',
      scheduledStart: 'Bắt đầu',
      scheduledEnd: 'Kết thúc',
      schedule: 'Lịch trình',
      status: 'Trạng thái',
      priority: 'Ưu tiên',
      estimatedDays: 'Số ngày dự kiến',
      notes: 'Ghi chú',
      riskLevel: 'Mức rủi ro',
      entityType: 'Loại',
      ownerUnit: 'Đơn vị chủ quản',
    },
    status: {
      planned: 'Kế hoạch',
      in_progress: 'Đang thực hiện',
      completed: 'Hoàn thành',
      deferred: 'Tạm hoãn',
      cancelled: 'Đã hủy',
    } as Record<string, string>,
    priority: {
      high: 'Cao',
      medium: 'Trung bình',
      low: 'Thấp',
    } as Record<string, string>,
  },
} as const;
