export const SETTINGS_LABELS = {
  orgUnit: {
    title: 'Đơn vị',
    titlePlural: 'Danh sách đơn vị',
    createTitle: 'Thêm đơn vị mới',
    editTitle: 'Chỉnh sửa đơn vị',
    deleteTitle: 'Xóa đơn vị',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa đơn vị "${name}"? Hành động này không thể hoàn tác.`,
    noData: 'Chưa có đơn vị nào.',
    search: 'Tìm kiếm đơn vị...',
    field: {
      name: 'Tên đơn vị',
      code: 'Mã đơn vị',
      parent: 'Trực thuộc',
      description: 'Mô tả',
      status: 'Trạng thái',
      established: 'Ngày thành lập',
      discontinued: 'Ngày giải thể',
      children: 'Đơn vị trực thuộc',
      leaderContact: 'Liên lạc',
      contactPointContact: 'Liên lạc',
      updatedAt: 'Cập nhật',
    },
    placeholder: {
      name: 'VD: Phòng Tài chính',
      code: 'VD: FIN',
      parent: 'Chọn đơn vị cha',
      description: 'Mô tả chức năng, nhiệm vụ của đơn vị...',
      noParent: 'Không có (Cấp cao nhất)',
    },
    section: {
      basic: 'Thông tin cơ bản',
      leader: 'Lãnh đạo đơn vị',
      contactPoint: 'Đầu mối liên hệ',
    },
    leader: {
      name: 'Họ và tên lãnh đạo',
      position: 'Chức vụ',
      email: 'Email lãnh đạo',
      phone: 'Số điện thoại lãnh đạo',
      status: 'Trạng thái',
      namePlaceholder: 'VD: Nguyễn Văn A',
      positionPlaceholder: 'VD: Giám đốc',
      addNew: 'Thêm lãnh đạo mới',
    },
    contactPoint: {
      name: 'Họ và tên đầu mối',
      position: 'Chức vụ',
      email: 'Email đầu mối',
      phone: 'Số điện thoại đầu mối',
      status: 'Trạng thái',
      namePlaceholder: 'VD: Trần Thị B',
      positionPlaceholder: 'VD: Chuyên viên',
      addNew: 'Thêm liên hệ mới',
    },
  },
  contact: {
    createTitle: 'Thêm liên hệ mới',
    editTitle: 'Chỉnh sửa liên hệ',
    noData: 'Chưa có liên hệ nào.',
    search: 'Tìm kiếm liên hệ...',
    status: {
      active: 'Đang làm việc',
      inactive: 'Đã nghỉ',
    },
    field: {
      unit: 'Đơn vị',
    },
    placeholder: {
      name: 'VD: Nguyễn Văn A',
      position: 'VD: Giám đốc',
      email: 'email@company.com',
      phone: 'VD: 024-1234-5678',
      unit: 'Chọn đơn vị (tùy chọn)',
      noUnit: 'Không thuộc đơn vị nào',
    },
  },
} as const;
