export const SETTINGS_LABELS = {
  orgUnit: {
    title: 'Đơn vị',
    titlePlural: 'Danh sách đơn vị',
    createTitle: 'Thêm đơn vị mới',
    editTitle: 'Chỉnh sửa đơn vị',
    deleteTitle: 'Xóa đơn vị',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa đơn vị "${name}"? Hành động này không thể hoàn tác.`,
    noData: 'Chưa có đơn vị nào.',
    search: 'Tìm kiếm đơn vị...',
    field: {
      name: 'Tên đơn vị',
      code: 'Mã đơn vị',
      parent: 'Trực thuộc',
      description: 'Mô tả',
      status: 'Trạng thái',
      established: 'Ngày thành lập',
      discontinued: 'Ngày giải thể',
      children: 'Đơn vị trực thuộc',
      leaderContact: 'Liên lạc',
      contactPointContact: 'Liên lạc',
      updatedAt: 'Cập nhật',
    },
    placeholder: {
      name: 'VD: Phòng Tài chính',
      code: 'VD: FIN',
      parent: 'Chọn đơn vị cha',
      description: 'Mô tả chức năng, nhiệm vụ của đơn vị...',
      noParent: 'Không có (Cấp cao nhất)',
    },
    section: {
      basic: 'Thông tin cơ bản',
      leader: 'Lãnh đạo đơn vị',
      contactPoint: 'Đầu mối liên hệ',
    },
    leader: {
      name: 'Họ và tên lãnh đạo',
      position: 'Chức vụ',
      email: 'Email lãnh đạo',
      phone: 'Số điện thoại lãnh đạo',
      status: 'Trạng thái',
      namePlaceholder: 'VD: Nguyễn Văn A',
      positionPlaceholder: 'VD: Giám đốc',
      addNew: 'Thêm lãnh đạo mới',
    },
    contactPoint: {
      name: 'Họ và tên đầu mối',
      position: 'Chức vụ',
      email: 'Email đầu mối',
      phone: 'Số điện thoại đầu mối',
      status: 'Trạng thái',
      namePlaceholder: 'VD: Trần Thị B',
      positionPlaceholder: 'VD: Chuyên viên',
      addNew: 'Thêm liên hệ mới',
    },
  },
  contact: {
    createTitle: 'Thêm liên hệ mới',
    editTitle: 'Chỉnh sửa liên hệ',
    noData: 'Chưa có liên hệ nào.',
    search: 'Tìm kiếm liên hệ...',
    status: {
      active: 'Đang làm việc',
      inactive: 'Đã nghỉ',
    },
    field: {
      unit: 'Đơn vị',
    },
    placeholder: {
      name: 'VD: Nguyễn Văn A',
      position: 'VD: Giám đốc',
      email: 'email@company.com',
      phone: 'VD: 024-1234-5678',
      unit: 'Chọn đơn vị (tùy chọn)',
      noUnit: 'Không thuộc đơn vị nào',
    },
  },
  riskCatalog: {
    title: 'Thư viện Rủi ro & Kiểm soát',
    description: 'Quản lý thư viện rủi ro, kiểm soát và thủ tục kiểm toán mẫu. Dữ liệu được chuẩn bị sẵn từ các khung quản trị (COBIT, COSO) và có thể tùy chỉnh.',
    tab: {
      risks: 'Rủi ro',
      controls: 'Kiểm soát',
      procedures: 'Thủ tục',
    },
    domain: {
      title: 'Lĩnh vực',
      titlePlural: 'Danh sách lĩnh vực',
      createTitle: 'Thêm lĩnh vực',
      editTitle: 'Chỉnh sửa lĩnh vực',
      deleteTitle: 'Xóa lĩnh vực',
      deleteDescription: (name: string) => `Bạn có chắc chắn muốn xóa lĩnh vực "${name}"? Tất cả danh mục và mục con sẽ bị xóa.`,
    },
    category: {
      title: 'Danh mục',
      titlePlural: 'Danh sách danh mục',
      createTitle: 'Thêm danh mục',
      editTitle: 'Chỉnh sửa danh mục',
      deleteTitle: 'Xóa danh mục',
      deleteDescription: (name: string) => `Bạn có chắc chắn muốn xóa danh mục "${name}"? Tất cả mục con sẽ bị xóa.`,
    },
    risk: {
      title: 'Rủi ro',
      createTitle: 'Thêm rủi ro mẫu',
      editTitle: 'Chỉnh sửa rủi ro',
      deleteTitle: 'Xóa rủi ro',
      deleteDescription: (name: string) => `Bạn có chắc chắn muốn xóa rủi ro "${name}"?`,
      noData: 'Chưa có rủi ro nào trong thư viện.',
    },
    control: {
      title: 'Kiểm soát',
      createTitle: 'Thêm kiểm soát mẫu',
      editTitle: 'Chỉnh sửa kiểm soát',
      deleteTitle: 'Xóa kiểm soát',
      deleteDescription: (name: string) => `Bạn có chắc chắn muốn xóa kiểm soát "${name}"?`,
      noData: 'Chưa có kiểm soát nào trong thư viện.',
    },
    procedure: {
      title: 'Thủ tục',
      createTitle: 'Thêm thủ tục mẫu',
      editTitle: 'Chỉnh sửa thủ tục',
      deleteTitle: 'Xóa thủ tục',
      deleteDescription: (name: string) => `Bạn có chắc chắn muốn xóa thủ tục "${name}"?`,
      noData: 'Chưa có thủ tục nào trong thư viện.',
    },
    field: {
      name: 'Tên',
      code: 'Mã',
      description: 'Mô tả',
      domain: 'Lĩnh vực',
      category: 'Danh mục',
      framework: 'Khung quản trị',
      frameworkRef: 'Tham chiếu',
      source: 'Nguồn',
      sourceSystem: 'Hệ thống',
      sourceCustom: 'Tùy chỉnh',
      riskType: 'Loại rủi ro',
      riskRating: 'Mức rủi ro',
      controlType: 'Loại kiểm soát',
      controlNature: 'Tính chất',
      frequency: 'Tần suất',
      procedureType: 'Loại thủ tục',
      procedureCategory: 'Phân loại',
      linkedControls: 'Kiểm soát liên quan',
      linkedRisks: 'Rủi ro liên quan',
      linkedProcedures: 'Thủ tục liên quan',
    },
    action: {
      addFromLibrary: 'Tìm từ thư viện',
      openFullForm: 'Mở form đầy đủ',
      addSelected: (count: number) => `Thêm ${count} mục đã chọn`,
    },
  },
} as const;
