export const UNIVERSE_LABELS = {
  entity: {
    title: 'Phạm vi tổng thể',
    titlePlural: 'Danh sách đối tượng kiểm toán',
    createTitle: 'Thêm đối tượng mới',
    editTitle: 'Chỉnh sửa đối tượng',
    deleteTitle: 'Xóa đối tượng',
    deleteDescription: (name: string) =>
      `Bạn có chắc chắn muốn xóa đối tượng "${name}"? Hành động này không thể hoàn tác.`,
    noData: 'Chưa có đối tượng kiểm toán nào.',
    search: 'Tìm kiếm đối tượng kiểm toán...',
    field: {
      name: 'Tên đối tượng',
      code: 'Mã',
      description: 'Mô tả',
      entityType: 'Loại',
      area: 'Lĩnh vực',
      ownerUnit: 'Đơn vị chủ quản',
      participatingUnits: 'Đơn vị phối hợp',
      status: 'Trạng thái',
      auditCycle: 'Chu kỳ kiểm toán',
      riskLevel: 'Mức độ rủi ro',
      riskImpact: 'Tác động',
      riskLikelihood: 'Khả năng xảy ra',
      riskScore: 'Điểm rủi ro',
      riskRationale: 'Lý do đánh giá',
      inherentRisk: 'Rủi ro tiềm tàng',
      inherentLevel: 'Mức rủi ro tiềm tàng',
      inherentImpact: 'Tác động',
      inherentLikelihood: 'Khả năng xảy ra',
      inherentScore: 'Điểm rủi ro tiềm tàng',
      controlEffectiveness: 'Hiệu quả kiểm soát',
      residualRisk: 'Rủi ro còn lại',
      residualScore: 'Điểm rủi ro còn lại',
      riskFactors: 'Yếu tố rủi ro',
      assessmentSource: 'Nguồn đánh giá',
      riskNote: 'Ghi chú',
      evaluatedBy: 'Người đánh giá',
      approvedBy: 'Người phê duyệt',
      evaluationDate: 'Ngày đánh giá',
      auditSponsor: 'Người bảo trợ kiểm toán',
      auditeeRep: 'Đại diện đơn vị',
      contactPoint: 'Đầu mối',
      lastAuditedAt: 'Kiểm toán gần nhất',
      createdAt: 'Ngày tạo',
      updatedAt: 'Cập nhật',
    },
    placeholder: {
      name: 'VD: Quy trình mua sắm',
      code: 'VD: PROC-001',
      description: 'Phạm vi, ranh giới, các hoạt động chính...',
      entityType: 'Chọn loại đối tượng',
      area: 'Chọn lĩnh vực',
      ownerUnit: 'Chọn đơn vị chủ quản',
      participatingUnits: 'Chọn đơn vị tham gia',
      auditCycle: 'Chọn chu kỳ',
      auditSponsor: 'VD: Nguyễn Văn A - GĐ Tài chính',
      auditeeRep: 'VD: Trần Thị B - GĐ Đơn vị',
      contactPoint: 'VD: Trần Thị B - TP Mua sắm',
      riskRationale: 'Lý do cho mức đánh giá rủi ro...',
      riskNote: 'Ghi chú thêm (không bắt buộc)...',
      evaluatedBy: 'Người đánh giá (chưa liên kết tài khoản)...',
      approvedBy: 'Người phê duyệt (chưa liên kết tài khoản)...',
    },
    action: {
      rateRisk: 'Đánh giá',
    },
    section: {
      basic: 'Thông tin cơ bản',
      units: 'Đơn vị',
      risk: 'Đánh giá rủi ro',
      contacts: 'Liên hệ chính',
      participatingUnits: 'Đơn vị tham gia',
      inherentRisk: 'Rủi ro tiềm tàng',
      controlEffectiveness: 'Môi trường kiểm soát',
      residualRisk: 'Rủi ro còn lại',
      assessmentContext: 'Thông tin đánh giá',
      assessmentMetadata: 'Thông tin xử lý',
    },
    status: {
      active: 'Đang hoạt động',
      inactive: 'Ngừng hoạt động',
      archived: 'Đã lưu trữ',
    },
    riskLevel: {
      Low: 'Thấp',
      Medium: 'Trung bình',
      High: 'Cao',
      Critical: 'Rất cao',
    },
    controlEffectiveness: {
      Strong: 'Tốt',
      Medium: 'Trung bình',
      Weak: 'Yếu',
    },
    // riskFactor and assessmentSource labels are now dynamic — fetched from DB
    // Use useRiskAssessmentFactors() and useAssessmentSources() hooks
    entityType: {
      Process: 'Quy trình',
      System: 'Hệ thống',
      'Business Unit': 'Đơn vị kinh doanh',
      Product: 'Sản phẩm',
      Project: 'Dự án',
      Function: 'Chức năng',
      'Third Party': 'Bên thứ ba',
    },
    auditCycle: {
      Annual: 'Hàng năm',
      Biennial: '2 năm',
      Triennial: '3 năm',
      'Ad-hoc': 'Đột xuất',
      Continuous: 'Liên tục',
    },
  },
} as const;
